name: Rclone Copy Flow 2
on:
  schedule:
    - cron: '30 */4 * * *'
  push:
    paths:
      - 'Flow/Rclone2.txt'    
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main          
       - name: Initialization
         continue-on-error: true
         run: |
           git config --global user.name ${{ secrets.GH_NAME }}
           git config --global user.email ${{ secrets.GH_MAIL }}
           git config --global credential.helper store
           echo "https://cosmosranger:${{ secrets.github.token }}@github.com" > ~/.git-credentials  
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ secrets.GH_TOKEN }}
       - name: Deploying and Running rclone
         timeout-minutes: 240
         continue-on-error: true
         uses: wei/rclone@master
         env:
           RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
         with:
           args: copy "kitty-edu:MBA" "CC-Media-MSG:MBA" --transfers 5 --checkers 5 --stats=10m --stats=15m --ignore-existing --drive-chunk-size 256M --drive-acknowledge-abuse --drive-stop-on-upload-limit
